"""Feature creation visualization: operation-type counts + per-feature table."""
from __future__ import annotations

from collections import Counter
from pathlib import Path

import plotly.graph_objects as go
from plotly.subplots import make_subplots

from backend.agents.feature_engineering.visuals.artifact_reader import ArtifactReader
from backend.agents.feature_engineering.visuals.base import BaseVisualizer

# Operations generated by the pipeline's own logic (excluded from user-facing creation chart)
INTERNAL_OPERATIONS = {"pca", "outlier_flag"}


class FeatureCreationVisualizer(BaseVisualizer):
    """Two-panel layout: operation type counts (left) and per-feature detail table (right)."""

    def build(self) -> go.Figure | None:
        all_created = self.reader.created_columns
        # Filter out pipeline-internal pseudo-operations
        user_created = [
            col for col in all_created
            if col.get("operation") not in INTERNAL_OPERATIONS
        ]
        if not user_created:
            return None

        mi_scores = self.reader.mi_scores

        operation_counts = Counter(col.get("operation", "unknown") for col in user_created)
        sorted_operations = sorted(operation_counts.keys(), key=lambda op: operation_counts[op])
        operation_bar_counts = [operation_counts[op] for op in sorted_operations]

        # Build table data
        feature_names: list[str] = []
        operation_names: list[str] = []
        sources_strings: list[str] = []
        avg_mi_strings: list[str] = []

        for created_col in user_created:
            col_name = created_col.get("name", "")
            operation = created_col.get("operation", "")
            sources = created_col.get("sources", [])
            source_mi_values = [mi_scores.get(src, 0.0) for src in sources]
            avg_mi = sum(source_mi_values) / len(source_mi_values) if source_mi_values else 0.0

            feature_names.append(col_name)
            operation_names.append(operation)
            sources_strings.append(", ".join(sources))
            avg_mi_strings.append(f"{avg_mi:.4f}")

        figure = make_subplots(
            rows=1, cols=2,
            column_widths=[0.35, 0.65],
            specs=[[{"type": "bar"}, {"type": "table"}]],
            subplot_titles=["Operations by Type", "Created Feature Details"],
        )

        figure.add_trace(
            go.Bar(
                name="Count",
                x=operation_bar_counts,
                y=sorted_operations,
                orientation="h",
                marker_color="#1f77b4",
                hovertemplate="Operation: %{y}<br>Count: %{x}<extra></extra>",
            ),
            row=1, col=1,
        )

        figure.add_trace(
            go.Table(
                header=dict(
                    values=["Name", "Operation", "Sources", "Avg Source MI"],
                    fill_color="#343a40",
                    font=dict(color="#ffffff", size=11),
                    align="left",
                ),
                cells=dict(
                    values=[feature_names, operation_names, sources_strings, avg_mi_strings],
                    fill_color="#f8f9fa",
                    align="left",
                    font=dict(size=10),
                ),
            ),
            row=1, col=2,
        )

        num_operations = len(sorted_operations)
        num_features = len(user_created)
        figure.update_layout(
            title=f"Created Features ({num_features} total, {num_operations} operation types)",
            height=max(400, max(num_features * 20, num_operations * 30) + 120),
            showlegend=False,
            margin=dict(l=20, r=20, t=80, b=20),
        )
        return figure
